#google_analytics_id: 

repository: https://github.com/aeciopires/jekyll
url: https://aeciopires.github.io/jekyll/

collections:
  docs:
    output: true
  posts:
    permalink: /news/:year/:month/:day/:title/
    output: true

name: Puppet-BR • Apenas um teste para o novo site

description: Site da comunidade Puppet-BR

logo: /img/puppet-users-br.png 

gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - README.md
  - .gitignore

theme: jekyll-theme-cayman
