#google_analytics_id: UA-50755011-1
google_site_verification: onQcXpAvtHBrUI5LlroHNE_FP0b2qvFyPq7VZw36iEY

repository: https://github.com/aeciopires/jekyll
help_url: https://github.com/jekyll/jekyll-help

collections:
  docs:
    output: true
  posts:
    permalink: /news/:year/:month/:day/:title/
    output: true

name: Jekyll • Simple, blog-aware, static sites
description: Transform your plain text into static websites and blogs
url: https://aeciopires.github.io/jekyll/

logo: /img/logo-2x.png

gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - README.md
  - .gitignore

theme: jekyll-theme-cayman
